sudo: required
language: java
jdk:
    - oraclejdk8

before_install:
    - chmod +x install_locally.sh
    - "./install_locally.sh"

after_success:
    - pwd
    - ls -ltr
    - ls -ltr target/
    - chmod 777 target/rates_server-1.0-SNAPSHOT.war

before_deploy:
    - pwd
    - ls -ltr

deploy:
  - provider: codedeploy
    access_key_id: $key_id
    secret_access_key: $secure_access_key
    bundle: target/rates_server-1.0-SNAPSHOT.war
    bundle_type: zip
    application_name: rates_server
    deployment_group: $deployment_grp
    skip_cleanup: true
    wait-until-deployed: true
