sudo: required
language: java
jdk:
  - oraclejdk8

before_install:
    - chmod +x install_locally.sh
    - ./install_locally.sh

deploy:
      - provider: s3
        access_key_id: AKIAJ4XZHIMNKP3WGGHQ
        secret_access_key: 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
        bucket: "elasticbeanstalk-us-west-2-511118469329"
        skip_cleanup: true
        on: &2
          repo: jayakrishnanra/rates_server
      - provider: codedeploy
        access_key_id: "AKIAJ7TWOCSOJEYEFHBQ"
        secret_access_key: "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"
        key: rates_server-1.0-SNAPSHOT.war
        bundle_type: war
        application: rates_server
        bucket: "elasticbeanstalk-us-west-2-511118469329"
        deployment_group: rates_server_grp
        wait-until-deployed: true
        region: us-east-1